server:
  port: 8082
  
spring:
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://192.168.1.216:8090
        predicates:
        - Path=/p1upgrade/**
        filters:
        - Pre